### PR TITLE
Refactor

### LINKED ISSUE #4: Path join issue
Hello

```
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
        ^
TypeError: Arguments to path.join must be strings
  at path.js:360:15
  at Array.filter (native)
  at Object.exports.join (path.js:358:36)
  at /Users/makc/GitHub/Maks/node_modules/metalsmith-duo/lib/index.js:26:22
  at Object.next [as _onImmediate] (/Users/makc/GitHub/Maks/node_modules/metalsmith/node_modules/ware/lib/index.js:68:8)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

I run in this issue when I run .use(duo()) with Metalsmith.
I have a simple style.css and main.js in my src folder.

With gratitude,
Maxim

### LINKED ISSUE #6: Absolute path for components copied into `./src` after build
This configuration: 

```json
{
  "plugins": {
    "metalsmith-in-place": {
      "engine": "swig"
    },
    "metalsmith-duo": {
      "css/index.css": "css/index.css",
      "js/index.js": "js/index.js"
    }
  }
}
```

Builds succesfully, but the components that duo downloads are stored in `./src/home/ismay/Github/website/components`. So it duplicates the absolute path, and it stores the components in `./src`, instead of `./components`.

By the way, changing [line 28](https://github.com/axyz/metalsmith-duo/blob/master/lib/index.js#L28) to:
```javascript
      install = ('components');
```
Stores the components in `./src/components`.

Maybe this is because you're not using the metalsmith API methods like `metalsmith.path()`, `metalsmith.source()`, `metalsmith.destination()`, but `metalsmith._destination`, etc.

### PR DESCRIPTION
**Pull request by ismay**
This plugin was doing several things that were causing unexpected or faulty behaviour. Major points were the use of metalsmith private variables where public methods exist, the use of absolute paths, and the disk operations (which aren't always useful in a metalsmith build chain).

I refactored it to consume an array of entry points. It won't do anything unless you specify at least one entry point, because I don't think it would be very useful to process everything if there are no arguments (could be slow, and not every file can be processed by duo).

It will process the entry points from the `files` object, and return the results to the `files` object (instead of writing it to disk), so that other plugins can do further manipulations on them.

Only thing missing now is allowing for optional configuration (like setting the `installTo` folder) and updating the readme. I'll see what I can do about that. It is kind of a major refactor, but it's the best way I could think of to get everything working as expected. Let me know if you have any suggestions, questions, etc!

closes #4, closes #6

### CODE REVIEW

**Comment by ismay** [comment]
So, passing options and plugins to duo now works as well. Also, I've added some tests. Only the readme needs to be updated now, and it would be a good idea to enable travis CI (as that would be trivial to add now that the tests are written and functional).

Let me know what you think of the changes.

**Comment by ismay** [comment]
@axyz Any feedback on this? I'd love for this to be merged, so let me know if you have any questions or anything.

**Comment by axyz** [comment]
It looks great, but I'm out of my city right now and I've only checkede it with my phone. I've not used very much this project recently, and as you have also provided some tests I guess  i will merge it for sure as soon I get back in Rome this week. Thanks for your effort



—
Andrea Moretti (@axyz)

**Comment by ismay** [comment]
Cool, you're welcome and thanks for the reply!

**Comment by ismay** [comment]
Thanks for the merge! As a reminder, some things that still need to be done are updating the readme, adding travis would be nice, and [here](https://github.com/axyz/metalsmith-duo/blob/master/lib/index.js#L16) I forgot that the options object is one object, instead of three params.

**Pull request merged**
